production:
  auto_deploy_on: refs/heads/master
  environment: production
  production_environment: true

staging:
  auto_deploy_on: refs/heads/master
  environment: staging
  production_environment: false
